"""
Seed data — sourced from DDT example payloads.
Consumer users: Jane (ke) and John (za).
Operator RBAC users: use mock-token-admin, mock-token-analyst, mock-token-operator,
mock-token-wrong-store (see TOKEN_MAP).
"""
from __future__ import annotations

# ─── Token → User ID map ────────────────────────────────────────────────────
TOKEN_MAP: dict[str, str] = {
    "mock-token-jane": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    "mock-token-john": "b2c3d4e5-f6a7-8901-bcde-f12345678901",
    "mock-token-admin": "user-123",
    "mock-token-analyst": "user-analytics-1",
    "mock-token-operator": "user-orders-1",
    "mock-token-wrong-store": "user-wrong-store-1",
}
DEFAULT_USER_ID = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"  # Jane is default

MOCK_ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiJ9.bW9jay1qYW5l.mock-sig"
MOCK_REFRESH_TOKEN = "eyJhbGciOiJIUzI1NiJ9.bW9jay1qYW5lLXJlZnJlc2g.mock-sig"

# ─── Users ───────────────────────────────────────────────────────────────────
SEED_USERS: list[dict] = [
    {
        "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "email": "jane@example.com",
        "first_name": "Jane",
        "last_name": "Doe",
        "phone_number": "+254700000000",
        "is_active": True,
        "email_verified": True,
        "phone_verified": True,
        "market_id": "ke",
        "date_joined": "2025-01-15T08:00:00Z",
        "created_at": "2025-01-15T08:00:00Z",
    },
    {
        "id": "b2c3d4e5-f6a7-8901-bcde-f12345678901",
        "email": "john@example.com",
        "first_name": "John",
        "last_name": "Smith",
        "phone_number": "+27700000000",
        "is_active": True,
        "email_verified": True,
        "phone_verified": False,
        "market_id": "za",
        "date_joined": "2025-03-01T08:00:00Z",
        "created_at": "2025-03-01T08:00:00Z",
    },
]

# ─── Operator users (minimal account rows; RBAC in SEED_OPERATOR_USER_PROFILES) ─
SEED_OPERATOR_USERS: list[dict] = [
    {
        "id": "user-123",
        "email": "admin@rossa.mock",
        "first_name": "Admin",
        "last_name": "User",
        "phone_number": "",
        "is_active": True,
        "email_verified": True,
        "phone_verified": True,
        "market_id": "ke",
        "date_joined": "2026-01-01T08:00:00Z",
        "created_at": "2026-01-01T08:00:00Z",
    },
    {
        "id": "user-analytics-1",
        "email": "analyst@rossa.mock",
        "first_name": "Analytics",
        "last_name": "Only",
        "phone_number": "",
        "is_active": True,
        "email_verified": True,
        "phone_verified": True,
        "market_id": "ke",
        "date_joined": "2026-01-02T08:00:00Z",
        "created_at": "2026-01-02T08:00:00Z",
    },
    {
        "id": "user-orders-1",
        "email": "operator@rossa.mock",
        "first_name": "Orders",
        "last_name": "Viewer",
        "phone_number": "",
        "is_active": True,
        "email_verified": True,
        "phone_verified": True,
        "market_id": "ke",
        "date_joined": "2026-01-03T08:00:00Z",
        "created_at": "2026-01-03T08:00:00Z",
    },
    {
        "id": "user-wrong-store-1",
        "email": "wrongstore@rossa.mock",
        "first_name": "Wrong",
        "last_name": "Store",
        "phone_number": "",
        "is_active": True,
        "email_verified": True,
        "phone_verified": True,
        "market_id": "ke",
        "date_joined": "2026-01-04T08:00:00Z",
        "created_at": "2026-01-04T08:00:00Z",
    },
]

# ─── Operator user profiles (RBAC: role, permissions, allowed stores) ────────
SEED_OPERATOR_USER_PROFILES: list[dict] = [
    {
        "id": "user-123",
        "role": "admin",
        "permissions": [
            "orders:view",
            "orders:update",
            "orders:delete",
            "orders:export",
            "menu:view",
            "menu:manage",
            "staff:view",
            "staff:manage",
            "analytics:view",
            "analytics:export",
            "stores:access_all",
            "stores:manage",
            "settings:view",
            "settings:manage",
        ],
        "allowed_stores": ["store-a", "store-b"],
    },
    {
        "id": "user-analytics-1",
        "role": "analyst",
        "permissions": ["analytics:view"],
        "allowed_stores": ["store-a"],
    },
    {
        "id": "user-orders-1",
        "role": "operator",
        "permissions": ["orders:view"],
        "allowed_stores": ["store-a"],
    },
    {
        "id": "user-wrong-store-1",
        "role": "admin",
        "permissions": ["orders:view", "analytics:view", "menu:view"],
        "allowed_stores": ["store-z"],
    },
]

# ─── Profiles ────────────────────────────────────────────────────────────────
SEED_PROFILES: list[dict] = [
    {
        "id": "prof-0001-0000-0000-000000000001",
        "account_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "market_id": "ke",
        "display_name": "Jane Doe",
        "avatar_url": "https://cdn.example.com/avatars/jane.jpg",
        "language": "en",
        "timezone": "Africa/Nairobi",
        "created_at": "2026-01-10T08:00:00Z",
        "updated_at": "2026-03-20T14:30:00Z",
    },
    {
        "id": "prof-0002-0000-0000-000000000002",
        "account_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901",
        "market_id": "za",
        "display_name": "John Smith",
        "avatar_url": None,
        "language": "en",
        "timezone": "Africa/Johannesburg",
        "created_at": "2026-03-01T08:00:00Z",
        "updated_at": "2026-03-01T08:00:00Z",
    },
]

# ─── Addresses ───────────────────────────────────────────────────────────────
SEED_ADDRESSES: list[dict] = [
    {
        "id": "addr-0001-0000-0000-000000000001",
        "account_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "label": "Home",
        "street": "14 Riverside Drive",
        "suburb": "Westlands",
        "city": "Nairobi",
        "postal_code": "00100",
        "country": "KE",
        "latitude": -1.2671,
        "longitude": 36.8103,
        "is_default": True,
        "deliverable": True,
        "created_at": "2026-01-15T08:00:00Z",
        "updated_at": "2026-02-10T12:00:00Z",
    },
    {
        "id": "addr-0002-0000-0000-000000000002",
        "account_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "label": "Office",
        "street": "The Oval, Ring Road Parklands",
        "suburb": None,
        "city": "Nairobi",
        "postal_code": "00100",
        "country": "KE",
        "latitude": -1.2595,
        "longitude": 36.8065,
        "is_default": False,
        "deliverable": True,
        "created_at": "2026-02-20T09:00:00Z",
        "updated_at": "2026-02-20T09:00:00Z",
    },
]

# ─── Market memberships ───────────────────────────────────────────────────────
SEED_MARKETS: list[dict] = [
    {
        "user_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "market_id": "ke",
        "status": "active",
        "activated_at": "2026-01-15T08:00:00Z",
    },
    {
        "user_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901",
        "market_id": "za",
        "status": "active",
        "activated_at": "2026-03-01T08:00:00Z",
    },
]

# ─── Onboarding checklists ────────────────────────────────────────────────────
SEED_CHECKLISTS: dict[str, dict] = {
    "ke": {
        "market_id": "ke",
        "status": "in_progress",
        "all_required_complete": False,
        "steps": [
            {"step": "phone_verification", "required": True, "completed": True},
            {"step": "id_verification", "required": True, "completed": False},
            {"step": "address_confirmation", "required": False, "completed": False},
        ],
    },
    "za": {
        "market_id": "za",
        "status": "complete",
        "all_required_complete": True,
        "steps": [
            {"step": "phone_verification", "required": True, "completed": True},
            {"step": "id_verification", "required": True, "completed": True},
        ],
    },
    "ng": {
        "market_id": "ng",
        "status": "not_started",
        "all_required_complete": False,
        "steps": [
            {"step": "phone_verification", "required": True, "completed": False},
            {"step": "id_verification", "required": True, "completed": False},
            {"step": "address_confirmation", "required": False, "completed": False},
        ],
    },
}

# ─── Consents ────────────────────────────────────────────────────────────────
SEED_CONSENTS: list[dict] = [
    {
        "user_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "consent_type": "marketing_email",
        "granted": True,
        "granted_at": "2026-01-15T08:00:00Z",
        "withdrawn_at": None,
    },
    {
        "user_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "consent_type": "data_analytics",
        "granted": True,
        "granted_at": "2026-01-15T08:00:00Z",
        "withdrawn_at": None,
    },
    {
        "user_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "consent_type": "third_party_sharing",
        "granted": False,
        "granted_at": None,
        "withdrawn_at": None,
    },
    {
        "user_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901",
        "consent_type": "marketing_email",
        "granted": True,
        "granted_at": "2026-03-01T08:00:00Z",
        "withdrawn_at": None,
    },
]

# ─── Restaurants ─────────────────────────────────────────────────────────────
SEED_RESTAURANTS: list[dict] = [
    {
        "id": "rest-001",
        "name": "KFC Westlands",
        "code": "NAI-WL-01",
        "address": "Westlands Square, Waiyaki Way",
        "location": {"lat": -1.2673, "lng": 36.8123},
        "city": "Nairobi",
        "postal_code": "00100",
        "country": "KE",
        "latitude": -1.2673,
        "longitude": 36.8123,
        "phone": "+254711000001",
        "email": "westlands@kfc.co.ke",
        "is_open": True,
        "is_active": True,
        "capabilities": ["pickup", "delivery"],
        "version": 3,
        "rating": 4.6,
        "review_count": 312,
        "distance_km": 1.2,
        "avg_preparation_minutes": 12,
        "delivery_fee": 150,
        "min_order_amount": 500,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/branches/westlands.jpg",
        "tags": ["fast-food", "chicken", "delivery"],
        "opening_hours": {"mon_fri": "08:00-22:00", "sat_sun": "09:00-23:00"},
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-03-15T10:00:00Z",
    },
    {
        "id": "rest-002",
        "name": "KFC CBD Towers",
        "code": "NAI-CBD-02",
        "address": "Anniversary Towers, University Way",
        "location": {"lat": -1.2864, "lng": 36.8226},
        "city": "Nairobi",
        "postal_code": "00200",
        "country": "KE",
        "latitude": -1.2864,
        "longitude": 36.8226,
        "phone": "+254711000002",
        "email": "cbd@kfc.co.ke",
        "is_open": True,
        "is_active": True,
        "capabilities": ["pickup", "dine-in"],
        "version": 2,
        "rating": 4.2,
        "review_count": 189,
        "distance_km": 3.7,
        "avg_preparation_minutes": 15,
        "delivery_fee": 200,
        "min_order_amount": 500,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/branches/cbd.jpg",
        "tags": ["fast-food", "chicken", "dine-in"],
        "opening_hours": {"mon_fri": "08:00-21:00", "sat_sun": "10:00-22:00"},
        "created_at": "2025-02-20T08:00:00Z",
        "updated_at": "2026-02-28T09:00:00Z",
    },
    {
        "id": "rest-003",
        "name": "KFC Sandton City",
        "code": "JHB-SC-01",
        "address": "Sandton City Mall, Rivonia Rd",
        "location": {"lat": -26.1071, "lng": 28.0567},
        "city": "Johannesburg",
        "postal_code": "2196",
        "country": "ZA",
        "latitude": -26.1071,
        "longitude": 28.0567,
        "phone": "+27110000003",
        "email": "sandton@kfc.co.za",
        "is_open": False,
        "is_active": True,
        "capabilities": ["pickup", "delivery"],
        "version": 1,
        "rating": 4.8,
        "review_count": 527,
        "distance_km": 8.4,
        "avg_preparation_minutes": 10,
        "delivery_fee": 35,
        "min_order_amount": 100,
        "currency": "ZAR",
        "image_url": "https://cdn.kfc-mock.com/branches/sandton.jpg",
        "tags": ["fast-food", "chicken", "delivery", "family"],
        "opening_hours": {"mon_fri": "09:00-22:00", "sat_sun": "09:00-23:00"},
        "created_at": "2024-11-01T08:00:00Z",
        "updated_at": "2026-04-01T06:00:00Z",
    },
    {
        "id": "rest-004",
        "name": "KFC Branch 4",
        "address": "515 Random Street",
        "city": "Mombasa",
        "postal_code": "00121",
        "country": "KE",
        "latitude": -16.4022,
        "longitude": 22.9517,
        "phone": "+254700000004",
        "email": "branch4@kfc.mock",
        "is_open": True,
        "rating": 4.9,
        "review_count": 487,
        "distance_km": 10.8,
        "avg_preparation_minutes": 28,
        "delivery_fee": 150,
        "min_order_amount": 500,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/branches/default.jpg",
        "tags": ["fast-food", "chicken", "delivery"],
        "opening_hours": {"mon_fri": "08:00-22:00", "sat_sun": "09:00-23:00"},
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-03-15T10:00:00Z",
    },
    {
        "id": "rest-005",
        "name": "KFC Branch 5",
        "address": "306 Random Street",
        "city": "Johannesburg",
        "postal_code": "00307",
        "country": "KE",
        "latitude": -20.2793,
        "longitude": 28.0965,
        "phone": "+254700000005",
        "email": "branch5@kfc.mock",
        "is_open": False,
        "rating": 3.5,
        "review_count": 994,
        "distance_km": 4.5,
        "avg_preparation_minutes": 22,
        "delivery_fee": 150,
        "min_order_amount": 500,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/branches/default.jpg",
        "tags": ["fast-food", "chicken", "delivery"],
        "opening_hours": {"mon_fri": "08:00-22:00", "sat_sun": "09:00-23:00"},
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-03-15T10:00:00Z",
    },
    {
        "id": "rest-006",
        "name": "KFC Branch 6",
        "address": "534 Random Street",
        "city": "Johannesburg",
        "postal_code": "00888",
        "country": "KE",
        "latitude": -11.1976,
        "longitude": -6.9053,
        "phone": "+254700000006",
        "email": "branch6@kfc.mock",
        "is_open": True,
        "rating": 4.1,
        "review_count": 625,
        "distance_km": 1.4,
        "avg_preparation_minutes": 24,
        "delivery_fee": 100,
        "min_order_amount": 500,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/branches/default.jpg",
        "tags": ["fast-food", "chicken", "delivery"],
        "opening_hours": {"mon_fri": "08:00-22:00", "sat_sun": "09:00-23:00"},
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-03-15T10:00:00Z",
    },
    {
        "id": "rest-007",
        "name": "KFC Branch 7",
        "address": "141 Random Street",
        "city": "Nairobi",
        "postal_code": "00211",
        "country": "KE",
        "latitude": -3.6821,
        "longitude": 31.1605,
        "phone": "+254700000007",
        "email": "branch7@kfc.mock",
        "is_open": True,
        "rating": 3.6,
        "review_count": 664,
        "distance_km": 1.4,
        "avg_preparation_minutes": 27,
        "delivery_fee": 50,
        "min_order_amount": 500,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/branches/default.jpg",
        "tags": ["fast-food", "chicken", "delivery"],
        "opening_hours": {"mon_fri": "08:00-22:00", "sat_sun": "09:00-23:00"},
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-03-15T10:00:00Z",
    },
    {
        "id": "rest-008",
        "name": "KFC Branch 8",
        "address": "579 Random Street",
        "city": "Nairobi",
        "postal_code": "00562",
        "country": "KE",
        "latitude": 2.2975,
        "longitude": 3.1451,
        "phone": "+254700000008",
        "email": "branch8@kfc.mock",
        "is_open": False,
        "rating": 4.6,
        "review_count": 727,
        "distance_km": 0.7,
        "avg_preparation_minutes": 28,
        "delivery_fee": 150,
        "min_order_amount": 500,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/branches/default.jpg",
        "tags": ["fast-food", "chicken", "delivery"],
        "opening_hours": {"mon_fri": "08:00-22:00", "sat_sun": "09:00-23:00"},
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-03-15T10:00:00Z",
    },
    {
        "id": "rest-009",
        "name": "KFC Branch 9",
        "address": "587 Random Street",
        "city": "Cape Town",
        "postal_code": "00296",
        "country": "KE",
        "latitude": 3.2184,
        "longitude": 27.4525,
        "phone": "+254700000009",
        "email": "branch9@kfc.mock",
        "is_open": True,
        "rating": 4.9,
        "review_count": 473,
        "distance_km": 2.4,
        "avg_preparation_minutes": 23,
        "delivery_fee": 50,
        "min_order_amount": 500,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/branches/default.jpg",
        "tags": ["fast-food", "chicken", "delivery"],
        "opening_hours": {"mon_fri": "08:00-22:00", "sat_sun": "09:00-23:00"},
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-03-15T10:00:00Z",
    },
    {
        "id": "rest-010",
        "name": "KFC Branch 10",
        "address": "543 Random Street",
        "city": "Mombasa",
        "postal_code": "00661",
        "country": "KE",
        "latitude": -28.4160,
        "longitude": 8.3157,
        "phone": "+254700000010",
        "email": "branch10@kfc.mock",
        "is_open": False,
        "rating": 4.5,
        "review_count": 928,
        "distance_km": 13.1,
        "avg_preparation_minutes": 11,
        "delivery_fee": 100,
        "min_order_amount": 500,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/branches/default.jpg",
        "tags": ["fast-food", "chicken", "delivery"],
        "opening_hours": {"mon_fri": "08:00-22:00", "sat_sun": "09:00-23:00"},
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-03-15T10:00:00Z",
    },
    {
        "id": "rest-011",
        "name": "KFC Branch 11",
        "address": "996 Random Street",
        "city": "Lagos",
        "postal_code": "00714",
        "country": "KE",
        "latitude": -2.4791,
        "longitude": -2.7079,
        "phone": "+254700000011",
        "email": "branch11@kfc.mock",
        "is_open": True,
        "rating": 3.6,
        "review_count": 201,
        "distance_km": 4.1,
        "avg_preparation_minutes": 13,
        "delivery_fee": 100,
        "min_order_amount": 500,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/branches/default.jpg",
        "tags": ["fast-food", "chicken", "delivery"],
        "opening_hours": {"mon_fri": "08:00-22:00", "sat_sun": "09:00-23:00"},
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-03-15T10:00:00Z",
    },
    {
        "id": "rest-012",
        "name": "KFC Branch 12",
        "address": "913 Random Street",
        "city": "Cape Town",
        "postal_code": "00705",
        "country": "KE",
        "latitude": -6.9205,
        "longitude": -0.4689,
        "phone": "+254700000012",
        "email": "branch12@kfc.mock",
        "is_open": True,
        "rating": 4.8,
        "review_count": 667,
        "distance_km": 4.6,
        "avg_preparation_minutes": 14,
        "delivery_fee": 200,
        "min_order_amount": 500,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/branches/default.jpg",
        "tags": ["fast-food", "chicken", "delivery"],
        "opening_hours": {"mon_fri": "08:00-22:00", "sat_sun": "09:00-23:00"},
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-03-15T10:00:00Z",
    },
    {
        "id": "rest-013",
        "name": "KFC Branch 13",
        "address": "170 Random Street",
        "city": "Mombasa",
        "postal_code": "00227",
        "country": "KE",
        "latitude": -17.3730,
        "longitude": 25.1857,
        "phone": "+254700000013",
        "email": "branch13@kfc.mock",
        "is_open": True,
        "rating": 4.7,
        "review_count": 541,
        "distance_km": 3.7,
        "avg_preparation_minutes": 25,
        "delivery_fee": 50,
        "min_order_amount": 500,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/branches/default.jpg",
        "tags": ["fast-food", "chicken", "delivery"],
        "opening_hours": {"mon_fri": "08:00-22:00", "sat_sun": "09:00-23:00"},
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-03-15T10:00:00Z",
    },
    {
        "id": "rest-014",
        "name": "KFC Branch 14",
        "address": "490 Random Street",
        "city": "Lagos",
        "postal_code": "00447",
        "country": "KE",
        "latitude": -14.8447,
        "longitude": 19.9635,
        "phone": "+254700000014",
        "email": "branch14@kfc.mock",
        "is_open": True,
        "rating": 4.0,
        "review_count": 197,
        "distance_km": 7.3,
        "avg_preparation_minutes": 16,
        "delivery_fee": 50,
        "min_order_amount": 500,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/branches/default.jpg",
        "tags": ["fast-food", "chicken", "delivery"],
        "opening_hours": {"mon_fri": "08:00-22:00", "sat_sun": "09:00-23:00"},
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-03-15T10:00:00Z",
    },
    {
        "id": "rest-015",
        "name": "KFC Branch 15",
        "address": "823 Random Street",
        "city": "Mombasa",
        "postal_code": "00616",
        "country": "KE",
        "latitude": -1.5883,
        "longitude": 3.2227,
        "phone": "+254700000015",
        "email": "branch15@kfc.mock",
        "is_open": True,
        "rating": 3.7,
        "review_count": 162,
        "distance_km": 3.5,
        "avg_preparation_minutes": 24,
        "delivery_fee": 50,
        "min_order_amount": 500,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/branches/default.jpg",
        "tags": ["fast-food", "chicken", "delivery"],
        "opening_hours": {"mon_fri": "08:00-22:00", "sat_sun": "09:00-23:00"},
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-03-15T10:00:00Z",
    },
    {
        "id": "rest-016",
        "name": "KFC Branch 16",
        "address": "943 Random Street",
        "city": "Nairobi",
        "postal_code": "00194",
        "country": "KE",
        "latitude": -13.1032,
        "longitude": 12.2127,
        "phone": "+254700000016",
        "email": "branch16@kfc.mock",
        "is_open": True,
        "rating": 4.5,
        "review_count": 214,
        "distance_km": 5.1,
        "avg_preparation_minutes": 29,
        "delivery_fee": 200,
        "min_order_amount": 500,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/branches/default.jpg",
        "tags": ["fast-food", "chicken", "delivery"],
        "opening_hours": {"mon_fri": "08:00-22:00", "sat_sun": "09:00-23:00"},
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-03-15T10:00:00Z",
    },
    {
        "id": "rest-017",
        "name": "KFC Branch 17",
        "address": "482 Random Street",
        "city": "Nairobi",
        "postal_code": "00780",
        "country": "KE",
        "latitude": -14.0431,
        "longitude": 7.9053,
        "phone": "+254700000017",
        "email": "branch17@kfc.mock",
        "is_open": False,
        "rating": 4.3,
        "review_count": 400,
        "distance_km": 14.0,
        "avg_preparation_minutes": 25,
        "delivery_fee": 150,
        "min_order_amount": 500,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/branches/default.jpg",
        "tags": ["fast-food", "chicken", "delivery"],
        "opening_hours": {"mon_fri": "08:00-22:00", "sat_sun": "09:00-23:00"},
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-03-15T10:00:00Z",
    },
    {
        "id": "rest-018",
        "name": "KFC Branch 18",
        "address": "559 Random Street",
        "city": "Johannesburg",
        "postal_code": "00399",
        "country": "KE",
        "latitude": 4.0670,
        "longitude": -2.2885,
        "phone": "+254700000018",
        "email": "branch18@kfc.mock",
        "is_open": True,
        "rating": 3.9,
        "review_count": 64,
        "distance_km": 12.3,
        "avg_preparation_minutes": 19,
        "delivery_fee": 100,
        "min_order_amount": 500,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/branches/default.jpg",
        "tags": ["fast-food", "chicken", "delivery"],
        "opening_hours": {"mon_fri": "08:00-22:00", "sat_sun": "09:00-23:00"},
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-03-15T10:00:00Z",
    },
    {
        "id": "rest-019",
        "name": "KFC Branch 19",
        "address": "572 Random Street",
        "city": "Nairobi",
        "postal_code": "00844",
        "country": "KE",
        "latitude": 1.8140,
        "longitude": 33.6512,
        "phone": "+254700000019",
        "email": "branch19@kfc.mock",
        "is_open": True,
        "rating": 4.0,
        "review_count": 281,
        "distance_km": 3.1,
        "avg_preparation_minutes": 26,
        "delivery_fee": 50,
        "min_order_amount": 500,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/branches/default.jpg",
        "tags": ["fast-food", "chicken", "delivery"],
        "opening_hours": {"mon_fri": "08:00-22:00", "sat_sun": "09:00-23:00"},
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-03-15T10:00:00Z",
    },
    {
        "id": "rest-020",
        "name": "KFC Branch 20",
        "address": "303 Random Street",
        "city": "Nairobi",
        "postal_code": "00239",
        "country": "KE",
        "latitude": 8.5152,
        "longitude": 10.0662,
        "phone": "+254700000020",
        "email": "branch20@kfc.mock",
        "is_open": True,
        "rating": 4.3,
        "review_count": 407,
        "distance_km": 2.9,
        "avg_preparation_minutes": 10,
        "delivery_fee": 150,
        "min_order_amount": 500,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/branches/default.jpg",
        "tags": ["fast-food", "chicken", "delivery"],
        "opening_hours": {"mon_fri": "08:00-22:00", "sat_sun": "09:00-23:00"},
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-03-15T10:00:00Z",
    },
]

# ─── Catalog Categories ───────────────────────────────────────────────────────
SEED_CATALOG_CATEGORIES: list[dict] = [
    {
        "id": "cat-001",
        "name": "Burgers",
        "slug": "burgers",
        "description": "Flame-grilled and crispy chicken burgers",
        "image_url": "https://cdn.kfc-mock.com/categories/burgers.jpg",
        "sort_order": 1,
        "is_active": True,
        "created_at": "2025-01-01T00:00:00Z",
        "updated_at": "2025-01-01T00:00:00Z",
    },
    {
        "id": "cat-002",
        "name": "Combos",
        "slug": "combos",
        "description": "Value meal combos with drink and side",
        "image_url": "https://cdn.kfc-mock.com/categories/combos.jpg",
        "sort_order": 2,
        "is_active": True,
        "created_at": "2025-01-01T00:00:00Z",
        "updated_at": "2025-01-01T00:00:00Z",
    },
    {
        "id": "cat-003",
        "name": "Sides",
        "slug": "sides",
        "description": "Fries, coleslaw, mashed potatoes and more",
        "image_url": "https://cdn.kfc-mock.com/categories/sides.jpg",
        "sort_order": 3,
        "is_active": True,
        "created_at": "2025-01-01T00:00:00Z",
        "updated_at": "2025-01-01T00:00:00Z",
    },
    {
        "id": "cat-004",
        "name": "Drinks",
        "slug": "drinks",
        "description": "Soft drinks, juices, and milkshakes",
        "image_url": "https://cdn.kfc-mock.com/categories/drinks.jpg",
        "sort_order": 4,
        "is_active": True,
        "created_at": "2025-01-01T00:00:00Z",
        "updated_at": "2025-01-01T00:00:00Z",
    },
    {
        "id": "cat-005",
        "name": "Desserts",
        "slug": "desserts",
        "description": "Ice cream, sundaes, and sweet treats",
        "image_url": "https://cdn.kfc-mock.com/categories/desserts.jpg",
        "sort_order": 5,
        "is_active": True,
        "created_at": "2025-01-01T00:00:00Z",
        "updated_at": "2025-01-01T00:00:00Z",
    },
]

# ─── Menu Items ───────────────────────────────────────────────────────────────
SEED_MENU_ITEMS: list[dict] = [
    # -- Burgers --
    {
        "id": "item-001",
        "restaurant_id": "rest-001",
        "category_id": "cat-001",
        "name": "Zinger Burger",
        "description": "Spicy crispy chicken fillet with zinger sauce in a toasted bun",
        "price": 520,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/zinger-burger.jpg",
        "calories": 540,
        "is_available": True,
        "is_featured": True,
        "tags": ["spicy", "bestseller"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-002",
        "restaurant_id": "rest-001",
        "category_id": "cat-001",
        "name": "Tower Burger",
        "description": "Double crispy chicken fillets with hash brown and cheese",
        "price": 680,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/tower-burger.jpg",
        "calories": 720,
        "is_available": True,
        "is_featured": False,
        "tags": ["double", "indulgent"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-003",
        "restaurant_id": "rest-002",
        "category_id": "cat-001",
        "name": "Classic Chicken Burger",
        "description": "Original recipe chicken fillet with lettuce and mayo",
        "price": 450,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/classic-burger.jpg",
        "calories": 480,
        "is_available": True,
        "is_featured": False,
        "tags": ["classic", "mild"],
        "created_at": "2025-02-20T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    # -- Combos --
    {
        "id": "item-004",
        "restaurant_id": "rest-001",
        "category_id": "cat-002",
        "name": "Trilogy Box Meal",
        "description": "3 pieces original recipe chicken, large fries, large drink",
        "price": 1050,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/trilogy-box.jpg",
        "calories": 1340,
        "is_available": True,
        "is_featured": True,
        "tags": ["combo", "value", "bestseller"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-03-01T00:00:00Z",
    },
    {
        "id": "item-005",
        "restaurant_id": "rest-001",
        "category_id": "cat-002",
        "name": "Zinger Meal",
        "description": "Zinger burger, regular fries, and a medium drink",
        "price": 850,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/zinger-meal.jpg",
        "calories": 980,
        "is_available": True,
        "is_featured": True,
        "tags": ["spicy", "combo", "value"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-006",
        "restaurant_id": "rest-002",
        "category_id": "cat-002",
        "name": "Family Feast",
        "description": "8 pieces chicken, 2 large fries, 4 drinks, coleslaw",
        "price": 3200,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/family-feast.jpg",
        "calories": 4200,
        "is_available": True,
        "is_featured": False,
        "tags": ["family", "sharing", "value"],
        "created_at": "2025-02-20T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-007",
        "restaurant_id": "rest-003",
        "category_id": "cat-002",
        "name": "Streetwise Two Meal",
        "description": "2 pieces chicken with regular fries and drink",
        "price": 89,
        "currency": "ZAR",
        "image_url": "https://cdn.kfc-mock.com/items/streetwise-two.jpg",
        "calories": 820,
        "is_available": True,
        "is_featured": True,
        "tags": ["value", "combo", "south-africa"],
        "created_at": "2024-11-01T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    # -- Sides --
    {
        "id": "item-008",
        "restaurant_id": "rest-001",
        "category_id": "cat-003",
        "name": "Large Fries",
        "description": "Golden crispy fries, perfectly salted",
        "price": 200,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/large-fries.jpg",
        "calories": 430,
        "is_available": True,
        "is_featured": False,
        "tags": ["side", "vegetarian"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-009",
        "restaurant_id": "rest-001",
        "category_id": "cat-003",
        "name": "Coleslaw",
        "description": "Creamy fresh coleslaw garden side",
        "price": 120,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/coleslaw.jpg",
        "calories": 180,
        "is_available": True,
        "is_featured": False,
        "tags": ["side", "vegetarian"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-010",
        "restaurant_id": "rest-002",
        "category_id": "cat-003",
        "name": "Mashed Potatoes",
        "description": "Creamy buttery mashed potatoes with gravy",
        "price": 150,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/mashed-potato.jpg",
        "calories": 220,
        "is_available": True,
        "is_featured": False,
        "tags": ["side", "vegetarian", "comfort"],
        "created_at": "2025-02-20T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    # -- Drinks --
    {
        "id": "item-011",
        "restaurant_id": "rest-001",
        "category_id": "cat-004",
        "name": "Pepsi Large",
        "description": "Large Pepsi cola fountain drink",
        "price": 150,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/pepsi-large.jpg",
        "calories": 210,
        "is_available": True,
        "is_featured": False,
        "tags": ["drink", "cold"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-012",
        "restaurant_id": "rest-002",
        "category_id": "cat-004",
        "name": "Strawberry Milkshake",
        "description": "Thick and creamy strawberry milkshake",
        "price": 280,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/strawberry-shake.jpg",
        "calories": 420,
        "is_available": True,
        "is_featured": True,
        "tags": ["drink", "cold", "dessert-drink"],
        "created_at": "2025-02-20T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-013",
        "restaurant_id": "rest-003",
        "category_id": "cat-004",
        "name": "Tropika Juice",
        "description": "Chilled tropical fruit juice blend",
        "price": 22,
        "currency": "ZAR",
        "image_url": "https://cdn.kfc-mock.com/items/tropika-juice.jpg",
        "calories": 140,
        "is_available": True,
        "is_featured": False,
        "tags": ["drink", "cold", "south-africa"],
        "created_at": "2024-11-01T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    # -- Desserts --
    {
        "id": "item-014",
        "restaurant_id": "rest-001",
        "category_id": "cat-005",
        "name": "Oreo Krushем",
        "description": "Crushed Oreos blended with creamy ice cream",
        "price": 320,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/oreo-krushem.jpg",
        "calories": 480,
        "is_available": True,
        "is_featured": True,
        "tags": ["dessert", "cold", "sweet"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-015",
        "restaurant_id": "rest-002",
        "category_id": "cat-005",
        "name": "Chocolate Sundae",
        "description": "Vanilla soft serve with rich chocolate sauce",
        "price": 180,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/choc-sundae.jpg",
        "calories": 310,
        "is_available": False,
        "is_featured": False,
        "tags": ["dessert", "cold", "sweet"],
        "created_at": "2025-02-20T08:00:00Z",
        "updated_at": "2026-03-10T10:00:00Z",
    },
    {
        "id": "item-016",
        "restaurant_id": "rest-003",
        "category_id": "cat-005",
        "name": "Mini Doughnuts",
        "description": "Warm cinnamon-sugar mini doughnuts, 6 pack",
        "price": 35,
        "currency": "ZAR",
        "image_url": "https://cdn.kfc-mock.com/items/mini-donuts.jpg",
        "calories": 560,
        "is_available": True,
        "is_featured": True,
        "tags": ["dessert", "warm", "sweet", "south-africa"],
        "created_at": "2024-11-01T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-017",
        "restaurant_id": "rest-016",
        "category_id": "cat-001",
        "name": "Mock Meal 17",
        "description": "Delicious KFC mock meal for testing.",
        "price": 1330,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/default.jpg",
        "calories": 830,
        "is_available": False,
        "is_featured": False,
        "tags": ["mock", "test"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-018",
        "restaurant_id": "rest-009",
        "category_id": "cat-001",
        "name": "Mock Meal 18",
        "description": "Delicious KFC mock meal for testing.",
        "price": 465,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/default.jpg",
        "calories": 799,
        "is_available": True,
        "is_featured": False,
        "tags": ["mock", "test"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-019",
        "restaurant_id": "rest-001",
        "category_id": "cat-001",
        "name": "Mock Meal 19",
        "description": "Delicious KFC mock meal for testing.",
        "price": 1467,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/default.jpg",
        "calories": 612,
        "is_available": True,
        "is_featured": True,
        "tags": ["mock", "test"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-020",
        "restaurant_id": "rest-012",
        "category_id": "cat-001",
        "name": "Mock Meal 20",
        "description": "Delicious KFC mock meal for testing.",
        "price": 853,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/default.jpg",
        "calories": 1119,
        "is_available": True,
        "is_featured": True,
        "tags": ["mock", "test"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-021",
        "restaurant_id": "rest-011",
        "category_id": "cat-005",
        "name": "Mock Meal 21",
        "description": "Delicious KFC mock meal for testing.",
        "price": 421,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/default.jpg",
        "calories": 654,
        "is_available": True,
        "is_featured": False,
        "tags": ["mock", "test"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-022",
        "restaurant_id": "rest-014",
        "category_id": "cat-003",
        "name": "Mock Meal 22",
        "description": "Delicious KFC mock meal for testing.",
        "price": 1286,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/default.jpg",
        "calories": 1171,
        "is_available": False,
        "is_featured": False,
        "tags": ["mock", "test"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-023",
        "restaurant_id": "rest-010",
        "category_id": "cat-002",
        "name": "Mock Meal 23",
        "description": "Delicious KFC mock meal for testing.",
        "price": 1114,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/default.jpg",
        "calories": 688,
        "is_available": True,
        "is_featured": False,
        "tags": ["mock", "test"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-024",
        "restaurant_id": "rest-018",
        "category_id": "cat-001",
        "name": "Mock Meal 24",
        "description": "Delicious KFC mock meal for testing.",
        "price": 200,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/default.jpg",
        "calories": 557,
        "is_available": True,
        "is_featured": True,
        "tags": ["mock", "test"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-025",
        "restaurant_id": "rest-003",
        "category_id": "cat-005",
        "name": "Mock Meal 25",
        "description": "Delicious KFC mock meal for testing.",
        "price": 1269,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/default.jpg",
        "calories": 1188,
        "is_available": False,
        "is_featured": True,
        "tags": ["mock", "test"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-026",
        "restaurant_id": "rest-006",
        "category_id": "cat-003",
        "name": "Mock Meal 26",
        "description": "Delicious KFC mock meal for testing.",
        "price": 817,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/default.jpg",
        "calories": 1101,
        "is_available": True,
        "is_featured": True,
        "tags": ["mock", "test"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-027",
        "restaurant_id": "rest-019",
        "category_id": "cat-003",
        "name": "Mock Meal 27",
        "description": "Delicious KFC mock meal for testing.",
        "price": 289,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/default.jpg",
        "calories": 515,
        "is_available": False,
        "is_featured": True,
        "tags": ["mock", "test"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-028",
        "restaurant_id": "rest-004",
        "category_id": "cat-004",
        "name": "Mock Meal 28",
        "description": "Delicious KFC mock meal for testing.",
        "price": 1156,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/default.jpg",
        "calories": 1056,
        "is_available": True,
        "is_featured": False,
        "tags": ["mock", "test"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-029",
        "restaurant_id": "rest-005",
        "category_id": "cat-002",
        "name": "Mock Meal 29",
        "description": "Delicious KFC mock meal for testing.",
        "price": 346,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/default.jpg",
        "calories": 327,
        "is_available": True,
        "is_featured": True,
        "tags": ["mock", "test"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-030",
        "restaurant_id": "rest-012",
        "category_id": "cat-003",
        "name": "Mock Meal 30",
        "description": "Delicious KFC mock meal for testing.",
        "price": 1278,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/default.jpg",
        "calories": 547,
        "is_available": True,
        "is_featured": True,
        "tags": ["mock", "test"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-031",
        "restaurant_id": "rest-016",
        "category_id": "cat-004",
        "name": "Mock Meal 31",
        "description": "Delicious KFC mock meal for testing.",
        "price": 1051,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/default.jpg",
        "calories": 799,
        "is_available": False,
        "is_featured": True,
        "tags": ["mock", "test"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-032",
        "restaurant_id": "rest-018",
        "category_id": "cat-002",
        "name": "Mock Meal 32",
        "description": "Delicious KFC mock meal for testing.",
        "price": 1255,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/default.jpg",
        "calories": 710,
        "is_available": True,
        "is_featured": False,
        "tags": ["mock", "test"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-033",
        "restaurant_id": "rest-009",
        "category_id": "cat-004",
        "name": "Mock Meal 33",
        "description": "Delicious KFC mock meal for testing.",
        "price": 1364,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/default.jpg",
        "calories": 363,
        "is_available": True,
        "is_featured": True,
        "tags": ["mock", "test"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-034",
        "restaurant_id": "rest-018",
        "category_id": "cat-004",
        "name": "Mock Meal 34",
        "description": "Delicious KFC mock meal for testing.",
        "price": 657,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/default.jpg",
        "calories": 1003,
        "is_available": True,
        "is_featured": False,
        "tags": ["mock", "test"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-035",
        "restaurant_id": "rest-014",
        "category_id": "cat-005",
        "name": "Mock Meal 35",
        "description": "Delicious KFC mock meal for testing.",
        "price": 398,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/default.jpg",
        "calories": 1147,
        "is_available": True,
        "is_featured": True,
        "tags": ["mock", "test"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "item-036",
        "restaurant_id": "rest-015",
        "category_id": "cat-004",
        "name": "Mock Meal 36",
        "description": "Delicious KFC mock meal for testing.",
        "price": 613,
        "currency": "KES",
        "image_url": "https://cdn.kfc-mock.com/items/default.jpg",
        "calories": 327,
        "is_available": True,
        "is_featured": False,
        "tags": ["mock", "test"],
        "created_at": "2025-01-10T08:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
]

# ─── Orders ───────────────────────────────────────────────────────────────────
SEED_ORDERS: list[dict] = [
    # Jane — delivered order
    {
        "id": "ord-001",
        "user_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "restaurant_id": "rest-001",
        "status": "delivered",
        "payment_status": "paid",
        "payment_method": "card",
        "items": [
            {
                "menu_item_id": "item-004",
                "name": "Trilogy Box Meal",
                "image_url": "https://cdn.kfc-mock.com/items/trilogy-box.jpg",
                "quantity": 2,
                "unit_price": 1050,
                "subtotal": 2100,
            },
            {
                "menu_item_id": "item-009",
                "name": "Coleslaw",
                "image_url": "https://cdn.kfc-mock.com/items/coleslaw.jpg",
                "quantity": 2,
                "unit_price": 120,
                "subtotal": 240,
            },
        ],
        "subtotal": 2340,
        "delivery_fee": 150,
        "tax": 374,
        "total": 2864,
        "currency": "KES",
        "delivery_address": {
            "street": "14 Riverside Drive",
            "suburb": "Westlands",
            "city": "Nairobi",
            "postal_code": "00100",
            "country": "KE",
            "latitude": -1.2671,
            "longitude": 36.8103,
        },
        "special_instructions": "Extra napkins please",
        "estimated_delivery_minutes": 25,
        "placed_at": "2026-03-20T12:00:00Z",
        "updated_at": "2026-03-20T12:42:00Z",
    },
    # Jane — in-progress order
    {
        "id": "ord-002",
        "user_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "restaurant_id": "rest-001",
        "status": "preparing",
        "payment_status": "paid",
        "payment_method": "mpesa",
        "items": [
            {
                "menu_item_id": "item-001",
                "name": "Zinger Burger",
                "image_url": "https://cdn.kfc-mock.com/items/zinger-burger.jpg",
                "quantity": 1,
                "unit_price": 520,
                "subtotal": 520,
            },
            {
                "menu_item_id": "item-008",
                "name": "Large Fries",
                "image_url": "https://cdn.kfc-mock.com/items/large-fries.jpg",
                "quantity": 1,
                "unit_price": 200,
                "subtotal": 200,
            },
            {
                "menu_item_id": "item-011",
                "name": "Pepsi Large",
                "image_url": "https://cdn.kfc-mock.com/items/pepsi-large.jpg",
                "quantity": 1,
                "unit_price": 150,
                "subtotal": 150,
            },
        ],
        "subtotal": 870,
        "delivery_fee": 150,
        "tax": 139,
        "total": 1159,
        "currency": "KES",
        "delivery_address": {
            "street": "The Oval, Ring Road Parklands",
            "suburb": None,
            "city": "Nairobi",
            "postal_code": "00100",
            "country": "KE",
            "latitude": -1.2595,
            "longitude": 36.8065,
        },
        "special_instructions": "",
        "estimated_delivery_minutes": 20,
        "placed_at": "2026-04-01T20:55:00Z",
        "updated_at": "2026-04-01T21:05:00Z",
    },
    # Jane — cancelled order
    {
        "id": "ord-003",
        "user_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "restaurant_id": "rest-002",
        "status": "cancelled",
        "payment_status": "refunded",
        "payment_method": "card",
        "items": [
            {
                "menu_item_id": "item-006",
                "name": "Family Feast",
                "image_url": "https://cdn.kfc-mock.com/items/family-feast.jpg",
                "quantity": 1,
                "unit_price": 3200,
                "subtotal": 3200,
            }
        ],
        "subtotal": 3200,
        "delivery_fee": 200,
        "tax": 512,
        "total": 3912,
        "currency": "KES",
        "delivery_address": {
            "street": "14 Riverside Drive",
            "suburb": "Westlands",
            "city": "Nairobi",
            "postal_code": "00100",
            "country": "KE",
            "latitude": -1.2671,
            "longitude": 36.8103,
        },
        "special_instructions": "",
        "estimated_delivery_minutes": 30,
        "placed_at": "2026-03-15T18:00:00Z",
        "updated_at": "2026-03-15T18:10:00Z",
    },
    # John — pending order
    {
        "id": "ord-004",
        "user_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901",
        "restaurant_id": "rest-003",
        "status": "pending",
        "payment_status": "pending",
        "payment_method": "cash",
        "items": [
            {
                "menu_item_id": "item-007",
                "name": "Streetwise Two Meal",
                "image_url": "https://cdn.kfc-mock.com/items/streetwise-two.jpg",
                "quantity": 3,
                "unit_price": 89,
                "subtotal": 267,
            },
            {
                "menu_item_id": "item-016",
                "name": "Mini Doughnuts",
                "image_url": "https://cdn.kfc-mock.com/items/mini-donuts.jpg",
                "quantity": 2,
                "unit_price": 35,
                "subtotal": 70,
            },
        ],
        "subtotal": 337,
        "delivery_fee": 35,
        "tax": 54,
        "total": 426,
        "currency": "ZAR",
        "delivery_address": {
            "street": "10 Maude St",
            "suburb": "Sandton",
            "city": "Johannesburg",
            "postal_code": "2196",
            "country": "ZA",
            "latitude": -26.1043,
            "longitude": 28.0557,
        },
        "special_instructions": "Leave at the gate",
        "estimated_delivery_minutes": 18,
        "placed_at": "2026-04-01T21:00:00Z",
        "updated_at": "2026-04-01T21:00:00Z",
    },
    # John — confirmed order
    {
        "id": "ord-005",
        "user_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901",
        "restaurant_id": "rest-003",
        "status": "confirmed",
        "payment_status": "paid",
        "payment_method": "card",
        "items": [
            {
                "menu_item_id": "item-007",
                "name": "Streetwise Two Meal",
                "image_url": "https://cdn.kfc-mock.com/items/streetwise-two.jpg",
                "quantity": 1,
                "unit_price": 89,
                "subtotal": 89,
            },
            {
                "menu_item_id": "item-013",
                "name": "Tropika Juice",
                "image_url": "https://cdn.kfc-mock.com/items/tropika-juice.jpg",
                "quantity": 1,
                "unit_price": 22,
                "subtotal": 22,
            },
        ],
        "subtotal": 111,
        "delivery_fee": 35,
        "tax": 18,
        "total": 164,
        "currency": "ZAR",
        "delivery_address": {
            "street": "10 Maude St",
            "suburb": "Sandton",
            "city": "Johannesburg",
            "postal_code": "2196",
            "country": "ZA",
            "latitude": -26.1043,
            "longitude": 28.0557,
        },
        "special_instructions": "",
        "estimated_delivery_minutes": 15,
        "placed_at": "2026-03-28T11:00:00Z",
        "updated_at": "2026-03-28T11:08:00Z",
    },
]

# ─── Modifier Groups (GraphQL Catalog) ────────────────────────────────────────
SEED_MODIFIER_GROUPS: list[dict] = [
    {
        "id": "mg-001",
        "item_id": "item-001",
        "name": "Spice Level",
        "min_selections": 1,
        "max_selections": 1,
        "is_required": True,
        "modifiers": [
            {"id": "mod-001", "name": "Mild",      "price_adjustment": "0.00",  "is_active": True},
            {"id": "mod-002", "name": "Regular",   "price_adjustment": "0.00",  "is_active": True},
            {"id": "mod-003", "name": "Extra Hot", "price_adjustment": "0.00",  "is_active": True},
        ],
    },
    {
        "id": "mg-002",
        "item_id": "item-001",
        "name": "Sauce Choice",
        "min_selections": 0,
        "max_selections": 2,
        "is_required": False,
        "modifiers": [
            {"id": "mod-004", "name": "Zinger Sauce", "price_adjustment": "0.00",  "is_active": True},
            {"id": "mod-005", "name": "BBQ Sauce",    "price_adjustment": "0.00",  "is_active": True},
            {"id": "mod-006", "name": "Garlic Mayo",  "price_adjustment": "20.00", "is_active": True},
        ],
    },
    {
        "id": "mg-003",
        "item_id": "item-011",
        "name": "Size",
        "min_selections": 1,
        "max_selections": 1,
        "is_required": True,
        "modifiers": [
            {"id": "mod-007", "name": "Regular", "price_adjustment": "-30.00", "is_active": True},
            {"id": "mod-008", "name": "Large",   "price_adjustment": "0.00",   "is_active": True},
            {"id": "mod-009", "name": "XL",      "price_adjustment": "30.00",  "is_active": True},
        ],
    },
]

# ─── Store Overrides (GraphQL Catalog) ────────────────────────────────────────
SEED_STORE_OVERRIDES: list[dict] = [
    {
        "id": "so-001",
        "store_id": "rest-001",
        "menu_item_id": "item-002",
        "override_type": "price_override",
        "override_price": "599.00",
        "reason": "Promotional price at Westlands for Q2 campaign.",
        "effective_from": "2026-04-01T00:00:00Z",
        "effective_until": "2026-06-30T23:59:59Z",
    },
    {
        "id": "so-002",
        "store_id": "rest-003",
        "menu_item_id": "item-015",
        "override_type": "hidden",
        "override_price": None,
        "reason": "Item not stocked at this franchise location.",
        "effective_from": None,
        "effective_until": None,
    },
    {
        "id": "so-003",
        "store_id": "rest-002",
        "menu_item_id": "item-009",
        "override_type": "unavailable",
        "override_price": None,
        "reason": "Temporarily out of stock.",
        "effective_from": "2026-04-03T00:00:00Z",
        "effective_until": "2026-04-10T23:59:59Z",
    },
]
